### 本地正确测试access
POST http://localhost:80/access
Content-Type: application/json

{
  "timestamp": "123231232131",
  "token":"",
  "username": "{{name}}",
  "password": "{{password}}"
}

### 本地不匹配测试access
POST http://localhost:80/access
Content-Type: application/json

{
  "timestamp": "123231232131",
  "username": "{{name}}",
  "password": "-1"
}

### 姓名null测试
POST http://localhost:80/access
Content-Type: application/json

{
  "timestamp": "123231232131",
  "username": null,
  "password": "-1"
}

### 换token成功测试
POST http://localhost:80/access
Content-Type: application/json

{
  "timestamp": "123231232131",
  "token": "{{token}}",
  "username": null,
  "password": "-1"
}