### 本地正确测试comment获取
POST http://localhost:80/comment/v1/get
Content-Type: application/json

{
  "cid": 1587386242887917569,
  "module": "forums",
  "mode": "newest",
  "need_num": 10,
  "num_start": 0,
  "num_end": 9,
  "timestamp": "{{timestamp}}"
}
### 本地正确测试comment提交
POST http://localhost:80/comment/v1/add
Content-Type: application/json

{
  "module": "forums",
  "cid": 1588439703469469698,
  "timestamp": "{{timestamp}}",
  "username": "{{name}}",
  "text": "test",
  "token": "{{token}}"
}
