### 本地正确测试forums
POST http://localhost:80/forums
Content-Type: application/json

{
  "module": "forums",
  "mode": "newest",
  "need_num": 10,
  "num_start": 0,
  "num_end": 9,
  "timestamp": "{{$timestamp}}000"
}

### 本地正确测试forums/v1
POST http://localhost:80/forums/v1/get
Content-Type: application/json

{
  "module": "forums",
  "mode": "newest",
  "need_num": 10,
  "num_start": 0,
  "num_end": 9,
  "timestamp": "{{$timestamp}}000"
}

### 本地数量错误测试forums
POST http://localhost:80/forums
Content-Type: application/json

{
  "module": "forums",
  "mode": "newest",
  "need_num": 10,
  "num_start": 1,
  "num_end": 9,
  "timestamp": "{{$timestamp}}000"
}


### 本地模式错误测试forums
POST http://localhost:80/forums
Content-Type: application/json

{
  "module": "forums",
  "mode": "？？？",
  "need_num": 10,
  "num_start": 0,
  "num_end": 9,
  "timestamp": "{{$timestamp}}000"
}

### 本地模块错误测试forums
POST http://localhost:80/forums
Content-Type: application/json

{
  "module": "？？？",
  "mode": "newest",
  "need_num": 10,
  "num_start": 0,
  "num_end": 9,
  "timestamp": "{{$timestamp}}000"
}

### 添加成功测试
POST http://localhost:80/forums/v1/add
Content-Type: application/json

{
  "module": "forums",
  "token": "{{token}}",
  "username":"{{name}}",
  "text": "test",
  "timestamp": "{{$timestamp}}000",
  "title": "test"
}
