### 本地正确测试run_errands
POST http://localhost:80/run_errands/v1/get
Content-Type: application/json

{
  "module": "run_errands",
  "mode": "newest",
  "need_num": 10,
  "num_start": 0,
  "num_end": 9,
  "timestamp": "{{$timestamp}}000"
}
### 本地正确测试run_errands v1
POST http://localhost:80/run_errands/v1/get
Content-Type: application/json

{
  "module": "run_errands",
  "mode": "newest",
  "need_num": 10,
  "num_start": 0,
  "num_end": 9,
  "timestamp": "{{$timestamp}}000"
}



### 本地数量错误测试run_errands
POST http://localhost:80/run_errands/v1/get
Content-Type: application/json

{
  "module": "run_errands",
  "mode": "newest",
  "need_num": 10,
  "num_start": 1,
  "num_end": 9,
  "timestamp": "{{$timestamp}}000"
}


### 本地模式错误测试run_errands
POST http://localhost:80/run_errands/v1/get
Content-Type: application/json

{
  "module": "run_errands",
  "mode": "？？？",
  "need_num": 10,
  "num_start": 0,
  "num_end": 9,
  "timestamp": "{{$timestamp}}000"
}

### 正确添加测试
POST http://localhost:80/run_errands/v1/add
Content-Type: application/json

{
  "module": "run_errands",
  "token": "{{token}}",
  "username":"{{name}}",
  "price": "{{price}}",
  "text": "test",
  "timestamp": "{{$timestamp}}000",
  "title": "test"
}