### 本地正确测试secondhand
POST http://localhost:80/secondhand/v1/get
Content-Type: application/json

{
  "module": "secondhand",
  "mode": "newest",
  "need_num": 10,
  "num_start": 0,
  "num_end": 9,
  "timestamp": "{{timestamp}}"
}

### 本地正确测试secondhand v1
POST http://localhost:80/secondhand/v1/get
Content-Type: application/json

{
  "module": "secondhand",
  "mode": "newest",
  "need_num": 10,
  "num_start": 0,
  "num_end": 9,
  "timestamp": "{{timestamp}}"
}


### 本地数量错误测试secondhand
POST http://localhost:80/secondhand/v1/get
Content-Type: application/json

{
  "module": "secondhand",
  "mode": "newest",
  "need_num": 10,
  "num_start": 1,
  "num_end": 9,
  "timestamp": "{{timestamp}}"
}


### 本地模式错误测试secondhand
POST http://localhost:80/secondhand/v1/get
Content-Type: application/json

{
  "module": "secondhand",
  "mode": "？？？",
  "need_num": 10,
  "num_start": 0,
  "num_end": 9,
  "timestamp": "{{timestamp}}"
}