### 本地正确测试access
POST http://localhost:80/access
Content-Type: application/json

{
  "timestamp": "123231232131",
  "token": "",
  "username": "bszydxh",
  "password": "227695cd8ea3b7194e9c2cbd9eba4342"
}
### 本地不匹配测试access
POST http://localhost:80/access
Content-Type: application/json

{
  "timestamp": "123231232131",
  "username": "bszydxh",
  "password": "-1"
}
### 姓名null测试
POST http://localhost:80/access
Content-Type: application/json

{
  "timestamp": "123231232131",
  "username": null,
  "password": "-1"
}

### 换token成功测试
POST http://localhost:80/access
Content-Type: application/json

{
  "timestamp": "123231232131",
  "token": "ezmKHU3GlN1v7oM/t1cDd5Cmh36lf+4XQy4UCHnxWAMJuBMtPw+IQ6/4UU9FK/C1oOAn3C7b4VS9Mt8g73nTscdGz6CIiJYv7cRWMQLQVvX8j/SjRlxPEoflwP+SlAiKS2qhDgB6SxzAT0QwpetpOAz1ykBrRdsjdaUiaefSugQwtHvsbqL3/+8fWGQyErm8mC00vEr5Ak10rmUAA4w++eFmOBib4Sfz2VCVj/Ad5uzHyPwkC3v2EXAzTeqZJ7d8kuwpOzwEVJ3Ey10bUms8LcIYcqRjvCrdCZ9dg0h8PpPdJTSd56xwFBrh9uzffWVWWxrRXk3C+GCj8fApUjc8Ow==",
  "username": null,
  "password": "-1"
}